name: Gradle Android Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Setup Java Env
        uses: actions/setup-java@v4
        with:
         distribution: 'zulu' # See 'Supported distributions' for available options
         java-version: '21'
      - name: Enable Corepack
        run: corepack enable

      - name: Activate Yarn 4.9.1
        run: corepack prepare yarn@4.9.1 --activate

      - name: Verify Yarn version
        run: yarn --version
      - name: Install dependencies
        run: yarn install

      - name: Run Expo Prebuild (optional)
        run: npx expo prebuild

      - name: Build Packages
        shell: bash
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/*.apk
