name: Gradle Android Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Setup Java Env
        uses: actions/setup-java@v4
        with:
         distribution: 'zulu' # See 'Supported distributions' for available options
         java-version: '21'
      - name: Enable Corepack
        run: corepack enable
      #APK签名设置
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: keystore.jks
          encodedString: ${{ vars.KEYSTORE_BASE64 }}

      - name: Activate Yarn 4.9.1
        run: corepack prepare yarn@4.9.1 --activate

      - name: Verify Yarn version
        run: yarn --version
      - name: Install dependencies
        run: yarn install
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run Expo Prebuild (optional)
        run: npx expo prebuild
      - name: Download bundletool
        run: |
          curl -L -o bundletool.jar https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar
      - name: Build Packages
        shell: bash
        run: |
          cd android
          # ./gradlew assembleRelease
          # ./gradlew bundleRelease
          # ./gradlew clean assembleRelease --no-daemon
          ./gradlew clean
          ./gradlew bundleRelease --ks ${{ steps.android_keystore.outputs.filePath }} --ks-key-alias ${{ vars.KEY_ALIAS }} --ks-store-password ${{ vars.STORE_PASSWORD }} --ks-key-password ${{ vars.KEY_ALIAS }}
          cd -
          java -jar bundletool.jar build-apks \
          --bundle=android/app/build/outputs/bundle/release/app-release.aab \
          --output=cherry_studio.apks

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: |
           cherry_studio.apks
           # ./android/app/build/outputs/apk/release/*.apk
           # android/app/build/outputs/apk/**/release/*.apk
           # android/app/build/outputs/bundle/release/*.aab
